import { Product } from "../types/product";

export const productData: Product[] = [
  {
    id: 1,
    name: "Abobora",
    description: "Abobora cabotian",
    unit: "kg",
    price: 2.5,
    farmer: {
      id: 1,
      name: "João",
      phone: "6699999999",
      address: {
        cep: "12345678",
        street: "Rua A",
        number: 123,
        complement: "Apto 1",
        neighborhood: "Centro",
        city: "São Paulo",
        state: "SP",
      },
    },
    promotion: {
      id: 1,
      startDate: "2023-10-01",
      endDate: "2023-10-31",
      quantity: 100,
      amount: 250.0,
    },
  },
  {
    id: 2,
    name: "Batata",
    description: "Batata doce",
    unit: "kg",
    price: 3.0,
    farmer: {
      id: 2,
      name: "Maria",
      phone: "6688888888",
      address: {
        cep: "87654321",
        street: "Rua B",
        number: 456,
        complement: "Casa 2",
        neighborhood: "Jardim",
        city: "Rio de Janeiro",
        state: "RJ",
      },
    },
    promotion: {
      id: 2,
      startDate: "2023-11-01",
      endDate: "2023-11-30",
      quantity: 200,
      amount: 600.0,
    },
  },
  {
    id: 3,
    name: "Cenoura",
    description: "Cenoura orgânica",
    unit: "kg",
    price: 4.0,
    farmer: {
      id: 3,
      name: "Carlos",
      phone: "6677777777",
      address: {
        cep: "11223344",
        street: "Rua C",
        number: 789,
        complement: "Lote 3",
        neighborhood: "Vila",
        city: "Belo Horizonte",
        state: "MG",
      },
    },
    promotion: {
      id: 3,
      startDate: "2023-12-01",
      endDate: "2023-12-31",
      quantity: 150,
      amount: 450.0,
    },
  },
  {
    id: 4,
    name: "Beterraba",
    description: "Beterraba fresca",
    unit: "kg",
    price: 2.0,
    farmer: {
      id: 4,
      name: "Ana",
      phone: "6655555555",
      address: {
        cep: "99887766",
        street: "Rua D",
        number: 321,
        complement: "Sala 4",
        neighborhood: "Zona Sul",
        city: "Curitiba",
        state: "PR",
      },
    },
    promotion: {
      id: 4,
      startDate: "2023-10-15",
      endDate: "2023-11-15",
      quantity: 80,
      amount: 160.0,
    },
  },
  {
    id: 5,
    name: "Brócolis",
    description: "Brócolis orgânico",
    unit: "kg",
    price: 5.0,
    farmer: {
      id: 5,
      name: "Luiz",
      phone: "6644444444",
      address: {
        cep: "55667788",
        street: "Rua E",
        number: 654,
        complement: "Apto 5",
        neighborhood: "Zona Norte",
        city: "Porto Alegre",
        state: "RS",
      },
    },
    promotion: {
      id: 5,
      startDate: "2023-11-10",
      endDate: "2023-12-10",
      quantity: 120,
      amount: 600.0,
    },
  },
  {
    id: 6,
    name: "Espinafre",
    description: "Espinafre fresco",
    unit: "kg",
    price: 3.5,
    farmer: {
      id: 6,
      name: "Fernanda",
      phone: "6633333333",
      address: {
        cep: "22334455",
        street: "Rua F",
        number: 987,
        complement: "Casa 6",
        neighborhood: "Zona Leste",
        city: "Salvador",
        state: "BA",
      },
    },
    promotion: {
      id: 6,
      startDate: "2023-12-05",
      endDate: "2024-01-05",
      quantity: 90,
      amount: 315.0,
    },
  },
  {
    id: 7,
    name: "Abobrinha",
    description: "Abobrinha italiana",
    unit: "kg",
    price: 3.0,
    farmer: {
      id: 7,
      name: "Roberto",
      phone: "6622222222",
      address: {
        cep: "33445566",
        street: "Rua G",
        number: 111,
        complement: "Lote 7",
        neighborhood: "Zona Oeste",
        city: "Fortaleza",
        state: "CE",
      },
    },
    promotion: {
      id: 7,
      startDate: "2023-10-20",
      endDate: "2023-11-20",
      quantity: 110,
      amount: 330.0,
    },
  },
  {
    id: 8,
    name: "Pepino",
    description: "Pepino japonês",
    unit: "kg",
    price: 2.5,
    farmer: {
      id: 8,
      name: "Patrícia",
      phone: "6611111111",
      address: {
        cep: "44556677",
        street: "Rua H",
        number: 222,
        complement: "Apto 8",
        neighborhood: "Zona Sul",
        city: "Recife",
        state: "PE",
      },
    },
    promotion: {
      id: 8,
      startDate: "2023-11-15",
      endDate: "2023-12-15",
      quantity: 130,
      amount: 325.0,
    },
  },
  {
    id: 9,
    name: "Rúcula",
    description: "Rúcula orgânica",
    unit: "kg",
    price: 4.5,
    farmer: {
      id: 9,
      name: "Eduardo",
      phone: "6600000000",
      address: {
        cep: "55668899",
        street: "Rua I",
        number: 333,
        complement: "Sala 9",
        neighborhood: "Zona Norte",
        city: "Manaus",
        state: "AM",
      },
    },
    promotion: {
      id: 9,
      startDate: "2023-12-10",
      endDate: "2024-01-10",
      quantity: 140,
      amount: 630.0,
    },
  },
  {
    id: 10,
    name: "Couve",
    description: "Couve manteiga",
    unit: "kg",
    price: 2.0,
    farmer: {
      id: 10,
      name: "Sofia",
      phone: "6599999999",
      address: {
        cep: "77889900",
        street: "Rua J",
        number: 444,
        complement: "Apto 10",
        neighborhood: "Zona Leste",
        city: "Goiânia",
        state: "GO",
      },
    },
    promotion: {
      id: 10,
      startDate: "2023-11-20",
      endDate: "2023-12-20",
      quantity: 100,
      amount: 200.0,
    },
  },
];
