import { Productor } from "../types/produtor";

export const produtorData: Productor[] = [
  {
    id: 1,
    name: "João",
    phone: "6699999999",
    address: {
      cep: "12345678",
      street: "Rua A",
      number: 123,
      complement: "Apto 1",
      neighborhood: "Centro",
      city: "São Paulo",
      state: "SP",
    },
  },
  {
    id: 2,
    name: "Maria",
    phone: "6688888888",
    address: {
      cep: "87654321",
      street: "Rua B",
      number: 456,
      complement: "Casa 2",
      neighborhood: "Jardim",
      city: "Rio de Janeiro",
      state: "RJ",
    },
  },
  {
    id: 3,
    name: "Carlos",
    phone: "6677777777",
    address: {
      cep: "11223344",
      street: "Rua C",
      number: 789,
      complement: "Sala 3",
      neighborhood: "Vila Nova",
      city: "Belo Horizonte",
      state: "MG",
    },
  },
  {
    id: 4,
    name: "Ana",
    phone: "6655555555",
    address: {
      cep: "99887766",
      street: "Rua D",
      number: 321,
      complement: "Bloco B",
      neighborhood: "Parque",
      city: "Curitiba",
      state: "PR",
    },
  },
  {
    id: 5,
    name: "Pedro",
    phone: "6644444444",
    address: {
      cep: "55667788",
      street: "Rua E",
      number: 654,
      complement: "Casa 5",
      neighborhood: "Jardim das Flores",
      city: "Fortaleza",
      state: "CE",
    },
  },
  {
    id: 6,
    name: "Lucia",
    phone: "6633333333",
    address: {
      cep: "44332211",
      street: "Rua F",
      number: 987,
      complement: "Apto 6",
      neighborhood: "Vila Verde",
      city: "Salvador",
      state: "BA",
    },
  },
  {
    id: 7,
    name: "Roberto",
    phone: "6622222222",
    address: {
      cep: "22334455",
      street: "Rua G",
      number: 210,
      complement: "Casa 7",
      neighborhood: "Lagoa Azul",
      city: "Recife",
      state: "PE",
    },
  },
  {
    id: 8,
    name: "Fernanda",
    phone: "6611111111",
    address: {
      cep: "33445566",
      street: "Rua H",
      number: 543,
      complement: "Bloco C",
      neighborhood: "Praia do Sol",
      city: "Natal",
      state: "RN",
    },
  },
];
